In [0]:
import numpy as np

In [0]:
class n_queens_board():
  def __init__(self,n=8,print=False):
    self.size=n
    self.printing=False
    self.board=self.build_board(n)
    self.turn_number=0
    self.game_complete=0
  def build_board(self,n):
    board=np.zeros((n,n))
    return board
  def apply_placement(self,coord):
    self.board[coord[0],coord[1]]=1
    return self.board
  def examine_placement(self,board,coord):
    board2=board.copy()
    board2[coord[0],coord[1]]=1
    return board2
  def get_available_moves(self,board):
    coords=np.asarray(board==0).nonzero()
    coords=np.stack((coords[0],coords[1]),1)
    coords=np.reshape(coords,(-1,2))
    moves=[]
    for coord in coords:
      if self.is_legal(board,coord):
        moves.append(coord)

    return moves
  def is_legal(self,board,coords):
    row,col=coords[0],coords[1]
    #print(row,col)
    #print(np.sum(board[row,:]), np.sum(board[:,col]),np.sum(np.diagonal(board, offset=col-row, axis1=0, axis2=1)),np.sum(np.diagonal(np.fliplr(board), offset=self.size-col-row, axis1=0, axis2=1)))
    if np.sum(board[row,:])!=0:
      return False
    if np.sum(board[:,col])!=0:
      return False
    if(np.sum(np.diagonal(board, offset=col-row, axis1=0, axis2=1))!=0):
      return False
    if(np.sum(np.diagonal(np.fliplr(board), offset=self.size-col-row-1, axis1=0, axis2=1))!=0):
      return False
    return True
  def is_goal_state(self,board):
    if(np.sum(board)!=self.size):
      return False
    for i in range(self.size):
      if(np.sum(board[i,:])!=1 or np.sum(board[:,i]!=1)):
         return False
    for i in range(-self.size,self.size):
      if(np.sum(np.diagonal(board, offset=col-row, axis1=0, axis2=1))>1):
        return False  
    for i in range(-self.size,self.size):
      if(np.sum(np.diagonal(np.fliplr(board), offset=col-row, axis1=0, axis2=1))>1):
        return False  
    return()
  

In [0]:
b1=n_queens_board(8)

In [92]:
print(b1.board)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [93]:
b1.apply_placement([0,1])
b1.apply_placement([1,3])
b1.get_available_moves(b1.board)

[[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


[array([2, 0]),
 array([2, 5]),
 array([2, 6]),
 array([2, 7]),
 array([3, 0]),
 array([3, 2]),
 array([3, 6]),
 array([3, 7]),
 array([4, 2]),
 array([4, 4]),
 array([4, 7]),
 array([5, 0]),
 array([5, 2]),
 array([5, 4]),
 array([5, 5]),
 array([6, 0]),
 array([6, 2]),
 array([6, 4]),
 array([6, 5]),
 array([6, 6]),
 array([7, 0]),
 array([7, 2]),
 array([7, 4]),
 array([7, 5]),
 array([7, 6]),
 array([7, 7])]

In [0]:
#TODO: Use search to solve the problem for 1-2-3-4-8 Queens


In [0]:
#What code would you use to If we now had to place rooks as well?