In [0]:
import numpy as np
import heapq
from itertools import count

In [0]:
class Node():
  def __init__(self,value="A"):
    self.value=value
    self.children=[]
  def add_child(self,child,edge_weight=0):
    self.children.append((edge_weight,child))
    
class Stack:
  def __init__(self):
     self.items = []

  def isEmpty(self):
     return self.items == []

  def push(self, item):
     self.items.append(item)

  def pop(self):
    val=self.items[len(self.items)-1]
    self.items=self.items[:-1]
    return val

  def peek(self):
     return self.items[len(self.items)-1]

  def size(self):
     return len(self.items)
    
class Queue:
  def __init__(self):
     self.items = []

  def isEmpty(self):
     return self.items == []

  def push(self, item):
     self.items.append(item)

  def pop(self):
    val=self.items[0]
    self.items=self.items[1:]
    return val
      
  def peek(self):
     return self.items[0]

  def size(self):
     return len(self.items)

In [0]:
class tic_tac_toe_game():
  def __init__(self,n=3,print=False):
    self.size=n
    self.printing=False
    self.board=self.build_board(n)
    self.turn_number=0
    self.game_complete=0
  def build_board(self,n):
    board=np.zeros((n,n))
    return board
  def reset_board(self,n):
    self.board=np.zeros((n,n))
    self.turn_number=0

  def get_available_moves(self,board):
    coords=np.asarray(board==0).nonzero()
    coords=np.stack((coords[0],coords[1]),1)
    coords=np.reshape(coords,(-1,2))
    if (self.is_goal_state(board)!=0):
      return []
    return coords
      
  def is_move_legal(self,move,board):
    return board[move[0]][move[1]]==0
  def apply_move(self,move):
    #Move is legal
    if(self.turn_number % 2 ==0):
      self.board[move[0],move[1]]=1
    else:
      self.board[move[0],move[1]]=2
    self.turn_number=self.turn_number+1
  def examine_move(self,board,move,player):
    board2=board.copy()
    #Move is legal
    if(1):
      board2[move[0],move[1]]=player
    return board2
  def is_goal_state(self,board):
    #Will do in a second
    if(np.sum(board)>5*1+4*2-1):
      return 0.1
    for i in range(3):
      if(np.all(board[i,:]==1) or np.all(board[:,i]==1) or np.all(np.diag(board)==1) or np.all(np.diag(np.fliplr(board))==1)):
        return 1
      if(np.all(board[i,:]==2) or np.all(board[:,i]==2)or np.all(np.diag(board)==2)or np.all(np.diag(np.fliplr(board))==2)):
        return -1
    return 0
      

In [0]:
A=tic_tac_toe_game()

In [0]:
print(A.board)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [0]:
def minimax_with_move(board,maximizing,player):
    if(A.is_goal_state(board)!=0):
      return A.is_goal_state(board)
    if(maximizing>0):
      best_move=[]
      #print(A.get_available_moves(board),maximizing,player)

      maximum_score=-1000
      moveset=A.get_available_moves(board)
      np.random.shuffle(moveset)      
      for next_board_move in moveset:
        val=minimax(A.examine_move(board,next_board_move,player),0,3-player)
        #print(val,next_board_move)
        if val>maximum_score:
          maximum_score=val
          best_move=next_board_move
      return maximum_score,best_move
    else:
      #print(A.get_available_moves(board),maximizing,player)

      minimum_score=1000
      best_move=[]
      for next_board_move in A.get_available_moves(board):
        val=minimax(A.examine_move(board,next_board_move,player),1,3-player)
        if val<minimum_score:
          minimum_score=val
          best_move=next_board_move
        print(val,next_board_move)

      return minimum_score,best_move
    
def minimax(board,maximizing,player):
    if(A.is_goal_state(board)!=0):
      return A.is_goal_state(board)
    if(maximizing>0): 
      maximum_score=-1000
      moveset=A.get_available_moves(board)
      np.random.shuffle(moveset)
      for next_board_move in moveset:
        val=minimax(A.examine_move(board,next_board_move,player),0,3-player)
        if val>maximum_score:
          maximum_score=val
      return maximum_score
    else:
      minimum_score=1000
      for next_board_move in A.get_available_moves(board):
        val=minimax(A.examine_move(board,next_board_move,player),1,3-player)
        if val<minimum_score:
          minimum_score=val
      return minimum_score
  
  

In [0]:
A.reset_board(3)
print(A.board)
player=1
maximizing=1
while(A.is_goal_state(A.board)==0):
  val,move=minimax_with_move(A.board,maximizing,player)

  print(val,move)
  A.apply_move(move)
  print(A.board)

  if(A.is_goal_state(A.board)==0):
    val,move=minimax_with_move(A.board,1-maximizing,3-player)

    print(move)
    A.apply_move(move)
    print(A.board)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [0]:
# To do: Convert minimax code to code with alpha beta pruning
def minimax_with_move_AB(board,maximizing,player):
    if(A.is_goal_state(board)!=0):
      return A.is_goal_state(board)
    if(maximizing>0):
      best_move=[]
      maximum_score=-1000
      moveset=A.get_available_moves(board)
      np.random.shuffle(moveset)      
      for next_board_move in moveset:
        val=minimax(A.examine_move(board,next_board_move,player),0,3-player)
        if val>maximum_score:
          maximum_score=val
          best_move=next_board_move
      return maximum_score,best_move
    else:
      minimum_score=1000
      best_move=[]
      for next_board_move in A.get_available_moves(board):
        val=minimax(A.examine_move(board,next_board_move,player),1,3-player)
        if val<minimum_score:
          minimum_score=val
          best_move=next_board_move
        print(val,next_board_move)

      return minimum_score,best_move
    
def minimax_AB(board,maximizing,player):
    if(A.is_goal_state(board)!=0):
      return A.is_goal_state(board)
    if(maximizing>0): 
      maximum_score=-1000
      moveset=A.get_available_moves(board)
      np.random.shuffle(moveset)
      for next_board_move in moveset:
        val=minimax(A.examine_move(board,next_board_move,player),0,3-player)
        if val>maximum_score:
          maximum_score=val
      return maximum_score
    else:
      minimum_score=1000
      for next_board_move in A.get_available_moves(board):
        val=minimax(A.examine_move(board,next_board_move,player),1,3-player)
        if val<minimum_score:
          minimum_score=val
      return minimum_score