In [0]:
import numpy as np
import heapq
from itertools import count


In [0]:
class Node():
  def __init__(self,value="A"):
    self.value=value
    self.children=[]
  def add_child(self,child,edge_weight=0):
    self.children.append((edge_weight,child))
    
class Stack:
  def __init__(self):
     self.items = []

  def isEmpty(self):
     return self.items == []

  def push(self, item):
     self.items.append(item)

  def pop(self):
    val=self.items[len(self.items)-1]
    self.items=self.items[:-1]
    return val

  def peek(self):
     return self.items[len(self.items)-1]

  def size(self):
     return len(self.items)
    
class Queue:
  def __init__(self):
     self.items = []

  def isEmpty(self):
     return self.items == []

  def push(self, item):
     self.items.append(item)

  def pop(self):
    val=self.items[0]
    self.items=self.items[1:]
    return val
      
  def peek(self):
     return self.items[0]

  def size(self):
     return len(self.items)
    


In [0]:
class tile_game():
  def __init__(self,n=3,print=False):
    self.size=n
    self.printing=False
    self.board=self.build_board(n)
  def build_board(self,n):
    board=np.arange(n*n)
    np.random.shuffle(board)
    board=board.reshape((n,n))
    return board
  def get_available_moves(self,board):
    available_moves=[]
    for i in range(self.size*self.size):
      coords=np.where(board==i)
      if(coords[0]>0):
        available_moves.append(((coords[0],coords[1]),(coords[0]-1,coords[1])))
      if(coords[0]<self.size-1):
        available_moves.append(((coords[0],coords[1]),(coords[0]+1,coords[1])))
      if(coords[1]>0):
        available_moves.append(((coords[0],coords[1]),(coords[0],coords[1]-1)))
      if(coords[1]<self.size-1):
        available_moves.append(((coords[0],coords[1]),(coords[0],coords[1]+1)))
      
    return available_moves
  def is_move_legal(self):
    coords=np.where(self.board==0)
  def apply_move(self,board,swap):
    #Move is legal
    coords=np.where(board==0)
    if(1):
      board[swap[0][0],swap[0][1]],board[swap[1][0],swap[1][1]]=board[swap[1][0],swap[1][1]],board[swap[0][0],swap[0][1]]
    self.board=board
  def examine_move(self,board,swap):
    board2=board.copy()
    #Move is legal
    if(1):
      board2[swap[0][0],swap[0][1]],board2[swap[1][0],swap[1][1]]=board2[swap[1][0],swap[1][1]],board2[swap[0][0],swap[0][1]]
    return board2
  def is_goal_state(self,board):
    goal_board=np.reshape(np.arange(self.size*self.size),(self.size,self.size))
    return np.all(board==goal_board)
      
    

In [0]:
A=tile_game(3)

In [0]:
print(A.board)

[[3 2 8]
 [0 7 6]
 [1 5 4]]


In [0]:
def bfs(starting_board):
  visited={}
  nodes_expanded=0
  frontier=Queue()
  frontier.push(starting_board)
  print(starting_board)
  while(frontier!=[]):
    if(frontier.items==[]):
      break
    current_node=frontier.pop()
    nodes_expanded=nodes_expanded+1
    print(nodes_expanded)
    for move in A.get_available_moves(current_node):
      next_board=A.examine_move(current_node,move)
      #print(next_board)
      if(A.is_goal_state(next_board)):
        return next_board,nodes_expanded
      if(next_board.tostring() not in visited):
        frontier.push(next_board)
        visited[next_board.tostring()]=True

In [0]:
#print(bfs(A.board))


In [0]:
tiebreaker = count()

def my_heuristic(board):
  h_val=2*np.sum(board==np.reshape(np.arange(board.size),board.shape))
  return h_val
  

def Astar(starting_board):
  visited={}
  nodes_expanded=0
  depth=0
  frontier=[]
  heapq.heappush(frontier,(-1*my_heuristic(starting_board),depth,next(tiebreaker),starting_board))
  moveset=A.get_available_moves(starting_board)
  print(starting_board)
  while(frontier!=[]):
    if(frontier==[]):
      break
    value,node_depth,_,current_node=heapq.heappop(frontier)
    nodes_expanded=nodes_expanded+1
    #print(nodes_expanded)
    for move in moveset:
      next_board=A.examine_move(current_node,move)
      #print(next_board)
      if(A.is_goal_state(next_board)):
        return next_board,nodes_expanded,node_depth
      if(next_board.tostring() not in visited):
        heapq.heappush(frontier,(-1*my_heuristic(next_board)+node_depth+1,node_depth+1,next(tiebreaker),next_board))
        visited[next_board.tostring()]=True


In [0]:
Astar(A.board)

[[3 2 8]
 [0 7 6]
 [1 5 4]]


(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]), 90, 10)

In [1]:
#TODO design your own heuristic which will solve the problem with the fewest number of nodes expanded on average
tiebreaker = count()

def your_heuristic(board):
  h_val=2*np.sum(board==np.reshape(np.arange(board.size),board.shape))
  return h_val
  

def Astar_student(starting_board):
  visited={}
  nodes_expanded=0
  depth=0
  frontier=[]
  heapq.heappush(frontier,(-1*your_heuristic(starting_board),depth,next(tiebreaker),starting_board))
  moveset=A.get_available_moves(starting_board)
  print(starting_board)
  while(frontier!=[]):
    if(frontier==[]):
      break
    value,node_depth,_,current_node=heapq.heappop(frontier)
    nodes_expanded=nodes_expanded+1
    #print(nodes_expanded)
    for move in moveset:
      next_board=A.examine_move(current_node,move)
      #print(next_board)
      if(A.is_goal_state(next_board)):
        return next_board,nodes_expanded,node_depth
      if(next_board.tostring() not in visited):
        heapq.heappush(frontier,(-1*your_heuristic(next_board)+node_depth+1,node_depth+1,next(tiebreaker),next_board))
        visited[next_board.tostring()]=True

NameError: ignored