In [0]:
import numpy as np
from IPython.display import clear_output
import time
import signal



In [43]:
def signal_handler(signum, frame):
    raise Exception("Timed out!")
signal.signal(signal.SIGALRM, signal_handler)



<function __main__.signal_handler>

In [0]:
class random_Agent():
  def __init__(self,player):
    self.player=player
  def choose_move(self,game):
    poss_moves=game.get_legal_moves(self.player)
    np.random.shuffle(poss_moves)
    return poss_moves[0]
  
class player_Agent():
  def __init__(self,player):
    #Add global variables
    self.player=player
  def choose_move(self,game):
    #Your job is to modify the player agent however you want to beat the random player~99% of the time with a time limit of 10 seconds per move. The only restriction is you cannot modify the game board directly. Any projects that so that will be disqualified.
    poss_moves=game.get_legal_moves(self.player)
    np.random.shuffle(poss_moves)
    return poss_moves[0]

In [0]:
class tron_game():
  def __init__(self,n=10,typ=1):
    if(typ==1):
      self.size=n
    else:
      self.size=10
    self.typ=typ
    self.board=self.build_board(typ)
    self.turn_number=0
    self.game_complete=0
    self.player_one_position=[0,0]
    self.player_second_position=[self.size-1,self.size-1]
    self.Agent_1=random_Agent(1)
    self.Agent_2=random_Agent(2)
  def build_board(self,typ=1):
    if(typ==1):
      temp_board=np.zeros((self.size,self.size))
      temp_board[0,0]=1
      temp_board[self.size-1,self.size-1]=2
    if(typ==2):
      temp_board=np.zeros((10,10))
      temp_board[1,4]=1
      temp_board[8,4]=2
      temp_board[3:7,0:4]=8
      temp_board[3:7,6:]=8
     
      
    return temp_board
  def reset_game(self):
    self.board=self.build_board(self.typ)
  def get_player_position(self,player,board=None):
    if(board is None):
      board=self.board
    coords=np.asarray(board==player).nonzero()
    coords=np.stack((coords[0],coords[1]),1)
    coords=np.reshape(coords,(-1,2))
    return coords[0]
  def get_legal_moves(self,player,board=None):
    if(board is None):
      board=self.board
    
    prev=self.get_player_position(player)
    moves=[]
    if(prev[0]!=0 and board[prev[0]-1,prev[1]]==0):
      moves.append([prev[0]-1,prev[1]])
    if(prev[0]!=self.size-1 and board[prev[0]+1,prev[1]]==0):
      moves.append([prev[0]+1,prev[1]])
    if(prev[1]!=0 and board[prev[0],prev[1]-1]==0):
      moves.append([prev[0],prev[1]-1])
    if(prev[1]!=self.size-1 and board[prev[0],prev[1]+1]==0):
      moves.append([prev[0],prev[1]+1])
    return moves
  def apply_move(self,player,coordinate):
    prev=self.get_player_position(player)

    self.board[prev[0],prev[1]]=8
    self.board[coordinate[0],coordinate[1]]=player
      
  def examine_move(self,player,coordinate,board):
    board2=board.copy()
    prev=self.get_player_position(player,board2)
    board2[prev]=8
    board2[coordinate]=player
    return board2
  def play_game(self,nn=1,printing=True):
    wins_player_1=0
    wins_player_2=0

    for _ in range(nn):
      
      self.reset_game()

      while(1):
        poss_moves=my_TRON_game.get_legal_moves(1)
        if(not len(poss_moves)):
          if(printing):
            print("Player 2 wins")
          wins_player_2+=1
          break
        signal.alarm(10)   # Ten seconds
        try:
          move=self.Agent_1.choose_move(self)
        except Exception:
          print("Timed out!")
          print("Player 2 wins")
          wins_player_2+=1
          break
        
        #move=self.Agent_1.choose_move(self)
        my_TRON_game.apply_move(1,move)
        if(printing):
          print(my_TRON_game.board)
          time.sleep(.5)
          clear_output()

        poss_moves=my_TRON_game.get_legal_moves(2)
        if(not len(poss_moves)):
          if(printing):
            print("Player 1 wins")
          wins_player_1+=1
          break
        signal.alarm(10)   # Ten seconds
        try:
          move=self.Agent_2.choose_move(self)
        except Exception:
          print("Timed out!")
          print("Player 1 wins")
          wins_player_1+=1
          break
          
        my_TRON_game.apply_move(2,move)
        if(printing):
          print(my_TRON_game.board)
          time.sleep(.5)
          clear_output()
      signal.alarm(0)
    print(my_TRON_game.board)
    print("Player one has won : " + str(wins_player_1)+ " games")
    print("Player two has won : " + str(wins_player_2)+ " games")

In [0]:
my_TRON_game=tron_game(10,1)


In [74]:
print(my_TRON_game.board)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 2.]]


In [75]:
my_TRON_game.play_game(100,False)


[[8. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [8. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [8. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [8. 8. 8. 0. 0. 0. 0. 0. 0. 0.]
 [8. 1. 8. 0. 0. 0. 0. 2. 0. 0.]
 [8. 8. 8. 0. 0. 0. 8. 8. 0. 0.]
 [0. 0. 0. 0. 0. 0. 8. 8. 8. 8.]
 [0. 0. 0. 0. 0. 0. 0. 8. 8. 8.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 8.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 8.]]
Player one has won : 57 games
Player two has won : 43 games
